[workspace]
resolver = "2"
members = ["crates/models"]
default-members = []

[workspace.package]
edition = "2024"
repository = "https://github.com/yixone/pictxn/"

[workspace.dependencies]
# DB
sqlx = "0.8.5"

# Utils
uuid = "1.17.0"
chrono = "0.4.42"
