[workspace]
resolver = "2"
members = ["crates/models", "crates/scout"]
default-members = []

[workspace.package]
edition = "2024"
repository = "https://github.com/yixone/pictxn/"

[workspace.dependencies]
# Async
async-trait = "0.1.89"

# DB
sqlx = "0.8.5"

# Utils
uuid = "1.17.0"
chrono = "0.4.42"
