[package]
name = "db"
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[dependencies]
# Async
async-trait.workspace = true

# SQLX
sqlx = { workspace = true, features = ["sqlite", "runtime-tokio"] }

# Domain
models.workspace = true
